In [ ]:
import numpy as np

In [ ]:
import sys

# Create a list of 1000000 integers
list_1000000 = list(range(1000000))

# Create a Numpy array of 1000000 integers
array_1000000 = np.arange(1000000)

# Print the size of the list and the array in bytes
print(f'Size of list:{sys.getsizeof(list_1000000)} bytes')
print(f'Size of array: {array_1000000.nbytes} bytes')

# Time how long it takes to sum the list and the array
import time

# Sum the list
start_time = time.time()
sum_list = sum(list_1000000)
end_time = time.time()
list_sum_time = (end_time - start_time) * 1000

# Sum the array
start_time = time.time()
sum_array = np.sum(array_1000000)
end_time = time.time()
array_sum_time = (end_time - start_time) * 1000

# Print the time it took to sum the list and the array
print(f'Time to sum list: {list_sum_time:.2f} milliseconds')
print(f'Time to sum array: {array_sum_time:.2f} milliseconds')

Size of list:8000056 bytes
Size of array: 8000000 bytes
Time to sum list: 32.84 milliseconds
Time to sum array: 1.84 milliseconds


In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar = np.arange(4,10,2)
ar

array([4, 6, 8])

In [ ]:
# Create a 1D array

arr_1d = np.array([1,2,3,4,5])
print(arr_1d)
print(arr_1d[0])

[1 2 3 4 5]
1


In [ ]:
# Create 2D array

arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_1d.ndim

1

In [ ]:
arr_2d.ndim

2

In [ ]:
# Shape

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(f'Shape of arr_2d: {arr_2d.shape}')

Shape of arr_2d: (2, 3)


In [ ]:
# Data type(dtype)

arr_float = np.array([1.1,2.2,3.3], dtype = np.float64)
print(arr_float)                                            # float32 or float64
#print the data type
print(f'Data type of the array: {arr_float}')

[1.1 2.2 3.3]
Data type of the array: [1.1 2.2 3.3]


In [ ]:
# Data type(dtype)

arr_float = np.array([1.1,2.2,3.3], dtype = np.int64)
print(arr_float)                                            # int32 or int64
#print the data type
print(f'Data type of the array: {arr_float}')

[1 2 3]
Data type of the array: [1 2 3]


In [ ]:
# Create 3D array

arr_3d = np.zeros([2,3,4])
print(arr_3d)
print(arr_3d.dtype)
# print the size
print('Size of the array', arr_3d.size)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
float64
Size of the array 24


In [ ]:
# Create a 4D array

arr_4d = np.ones((2,3,4,5))
print(arr_4d)
# print the number of dimensions
print(f'No of dimensions: {arr_4d.ndim}')

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
No of dimensions: 4


In [ ]:
# Create a array of integers
arr_int = np.array((1,2,3))
print(arr_int.dtype)
# print the Item size
print('Size of the each element (in bytes):', arr_int.itemsize)

int64
Size of the each element (in bytes): 8


In [ ]:
# Create an array with a specific data type
arr_int32 = np.array((1,2,3), dtype=np.int32)
arr_float = np.array((1.1,2.2,3.3), dtype=np.float64)

print('Data type of arr_int32:', arr_int32.dtype)
print('Data type of arr_float64:', arr_float.dtype)

Data type of arr_int32: int32
Data type of arr_float64: float64


In [ ]:
# Precision:

# Create an array with different data types
arr_int32 = np.array((1234567890, 1234567890), dtype=np.int32)
arr_int64 = np.array((1234567890, 1234567890), dtype=np.int64)

print('Data type of arr_int32:', arr_int32.dtype)
print('Data type of arr_int64:', arr_int64.dtype)

print(arr_int32)

# in this example, the "int32" data type has limited precision compared to "int64", which can represent larger integers without loss of precision.

Data type of arr_int32: int32
Data type of arr_int64: int64
[1234567890 1234567890]


In [ ]:
# impact of precision on memory usage:
# Create an array with different data types
arr_float32 = np.array((1.1,2.2,3.3), dtype=np.float32)
arr_float64 = np.array((1.1,2.2,3.3), dtype=np.float64)

print('Memory usage of arr_float32:', arr_float32.itemsize * arr_float32.size,'bytes')    #(3 * 4 bytes/elements)
print('Memory usage of arr_float64:', arr_float64.itemsize * arr_float64.size,'bytes')    #(3 * 8 bytes/elements)


Memory usage of arr_float32: 12 bytes
Memory usage of arr_float64: 24 bytes


In [ ]:
# Create a large array with float32 and float64 data types
large_array_float32 = np.arange(1000000, dtype=np.float32)
large_array_float64 = np.arange(1000000, dtype=np.float64)

# Calculate the sum of elements
sum_float32 = np.sum(large_array_float32)
sum_float64 = np.sum(large_array_float64)

print('Sum using float32:', sum_float32)
print('Sum using float64:', sum_float64)

Sum using float32: 499999800000.0
Sum using float64: 499999500000.0


In [ ]:
# np.zeros, np.ones, np.full
zeros_array = np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_array = np.ones((3,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
full_array = np.full((2,2),5)
print(full_array)

[[5 5]
 [5 5]]


In [ ]:
# Arthemetic operations
# add
arr_sum = np.add([1,2,3],[4,5,6])
print('Addition',arr_sum)

# sub
arr_diff = np.subtract([5,6,7],[2,3,1])
print('Subtract',arr_diff)

# div
arr_div = np.divide([10,12,14],[4,5,6])
print('Division',arr_div)

# Modulus
arr_mod = np.mod([10,11,12],[4,5,6])
print('Modulus',arr_mod)

# Exponential
arr_pow = np.power([1,2,3],[4,5,6])
print('Power',arr_pow)


Addition [5 7 9]
Subtract [3 3 6]
Division [2.5        2.4        2.33333333]
Modulus [2 1 0]
Power [  1  32 729]


In [ ]:
# Relational operations
# Create sample arrays
arr1 = np.array((1,2,3,4))
arr2 = np.array((2,2,4,3))

# Equal
print('Equal:', arr1==arr2)

# Not equal
print('Equal:', arr1 != arr2)

# Greater than
print('Equal:', arr1 > arr2)

# Greater than or equal to
print('Equal:', arr1 >= arr2)

# Less than
print('Equal:', arr1 < arr2)

# Less than or equal to
print('Equal:', arr1 <= arr2)

Equal: [False  True False False]
Equal: [ True False  True  True]
Equal: [False False False  True]
Equal: [False  True False  True]
Equal: [ True False  True False]
Equal: [ True  True  True False]


In [ ]:
# Indexing and Slicing
arr = np.array((1,2,3,4,5))

print(arr[0])
print(arr[1])
print(arr[-1])

1
2
5


In [ ]:
arr = np.array((1,2,3,4,5))

print(arr[1:3])
print(arr[0:4:2])

[2 3]
[1 3]


In [ ]:
# Negative Indexing
arr = np.array((1,2,3,4,5))

print(arr[-1])

5


In [ ]:
# Slicing with Omitted Indices
arr = np.array((1,2,3,4,5))

print(arr[:3])
print(arr[2:])
print(arr[::2])

[1 2 3]
[3 4 5]
[1 3 5]


In [ ]:
# Indexing and Slicing for 2D Arrays
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [ ]:
# Slicing
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


In [ ]:
arr[0:2, 1:3] = [[10,20],[30,40]]

In [ ]:
arr

array([[ 1, 10, 20],
       [ 4, 30, 40],
       [ 7,  8,  9]])

In [ ]:
# Nagative Slicing
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr[-1, -1])

9


In [ ]:
# Nagative Slicing
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr[-3, -1])

3


In [ ]:
# Create a 1D array
arr_1d = np.array((1,2,3,4,5))

mask = arr_1d > 3

selected_elements = arr_1d[mask]
print('Selected elements',selected_elements)

In [ ]:
# Create a 2D array
arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
result_2d = arr_2d[arr_2d > 2]
print('Elements greater than 2 in 2D array:',result_2d)

In [ ]:
# Create a 2D array
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d.shape)

transposed_arr = arr_2d.T
print(transposed_arr)

(2, 3)
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Random Numbers
random_integers = np.random.randint(1,10, size=5)
random_integers

array([5, 6, 2, 7, 3])

In [ ]:
random_normal = np.random.normal(size=5)
random_normal

array([-1.08264924, -1.63904701,  0.26456181, -1.15025248, -0.88261323])

In [ ]:
# Matrix Multiplication
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[5,6],[7,8]])

result = np.matmul(matrix_a, matrix_b)
print('Matrix Multiplication')
print(result)

Matrix Multiplication
[[19 22]
 [43 50]]


In [ ]:
# Reshaping(np.reshape())
arr = np.arange(1, 10)
reshaped_arr = arr.reshape((3,3))
print('Reshaped array:')
print(reshaped_arr)

Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Aggregate Functions
matrix = np.array([[1,2,3],
                   [4,5,6]])
print('Sum of all elements:',np.sum(matrix))
print('Maximum elements:',np.max(matrix))
print('Minimum elements:',np.min(matrix))
print('mean of all elements:',np.mean(matrix))
print('Standard Deviation:',np.std(matrix))

Sum of all elements: 21
Maximum elements: 6
Minimum elements: 1
mean of all elements: 3.5
Standard Deviation: 1.707825127659933


In [ ]:
print(matrix)
flat = matrix.ravel()
print('Flattened array:',flat)

[[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]


In [ ]:
# Spliting
x = np.arange(9)

x_split = np.split(x, 3)
print("Split array:",x_split)

Split array: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
x_array_split = np.array_split(x, 4)
print('Array split into unequal parts:', x_array_split)

Array split into unequal parts: [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

concatenated = np.concatenate((a, b))
print(concatenated)

[1 2 3 4 5 6]
